version: "3.7"

services:
  chatbot-api:
    container_name: chatbot-api
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    volumes:
      - ./.env:/app/.env
    ports:
      - 9000:9000
    env_file:
      - .env
